### ISSUE TITLE
how do i add a label i forgot and this is a bug

### ISSUE THREAD

**Issue by Bardelby** [KitsueFox/PPDS-Mods#4]

**Comment by Bardelby** [comment]
oh
i set melonpreferences to true

**Comment by Bardelby** [comment]
on the achievements

**Comment by Bardelby** [comment]
but it still wont enable achievements

**Comment by KitsueFox** [comment]
make sure you check the spelling and case
![image](https://github.com/KitsueFox/PPDS-Mods/assets/80623201/05373c79-9d86-4834-a6ee-1fed1baf6944)

**Comment by KitsueFox** [comment]
I fixed it #6
